# Nome da Actions:
name: Snake Game

# Controlador do tempo que será feito na atualização dos arquivos
on:
  schedule:
    # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"
  # Permite executar manualmente na lista de Actions (utilizando para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do repositório, permitindo acesso aos arquivos
      - uses: actions/checkout@v2

      # Repositório que será utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: capriles
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
        
      # Verifica o status do repositório (opcional para debug)
      - run: git status

      # Para fazer push das atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Publica os arquivos gerados na branch de saída.
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
